name: ${project.name}
version: ${project.version}
main: org.bitbucket.ucchy.undine.UndineMailer
description: UndineMailer - Mail Plugin for ${release.lang}
softdepend: [Vault]
author: ucchy

commands:
  undine:
    description: Command of UndineMailer
    aliases: [mail,umail]
    usage: |
           /<command> inbox [page] - Check your unread mails.
           /<command> outbox [page] - Check your sent mails.
           /<command> text <to> <message> - Send simple text mail.
           /<command> write - Enter to mail creation mode.
           /<command> item - Show the detailed information of item in your hand.
           /<command> reload - Reload all of data.
    permission: undine.command
    permission-message: 'You don''t have a permission "<permission>".'

  undinelist:
    description: Command of Player list
    aliases: [ulist,uindex]
    usage: |
           /<command> - display player index button page.
    permission: undine.list
    permission-message: 'You don''t have a permission "<permission>".'

  undinegroup:
    description: Command of Mail group
    aliases: [ugroup]
    usage: |
           /<command> - display group management menu page.
    permission: undine.group.command
    permission-message: 'You don''t have a permission "<permission>".'

permissions:
  undine.command:
    description: Permission of command.
    default: true
  undine.inbox:
    description: Permission of inbox command.
    default: true
  undine.outbox:
    description: Permission of outbox command.
    default: true
  undine.read:
    description: Permission of read command.
    default: true
  undine.read-all:
    description: Permission of read other's mail.
    default: op
  undine.text:
    description: Permission of text command.
    default: true
  undine.write:
    description: Permission of write command.
    default: true
  undine.to:
    description: Permission of to command.
    default: true
  undine.message:
    description: Permission of message command.
    default: true
  undine.attach:
    description: Permission of attach command.
    default: true
  undine.attach-all:
    description: Permission of opening other's mail attach box.
    default: op
  undine.attach-infinity:
    description: Permission of infinity use of attachment box.
    default: op
  undine.costmoney:
    description: Permission of costmoney command.
    default: true
  undine.costitem:
    description: Permission of costitem command.
    default: true
  undine.send:
    description: Permission of send command.
    default: true
  undine.cancel:
    description: Permission of send command.
    default: true
  undine.item:
    description: Permission of item command.
    default: true
  undine.reload:
    description: Permission of reload command.
    default: op

  undine.list:
    description: Permission of list command.
    default: true

  undine.group.command:
    description: Permission of group command.
    default: true
  undine.group.create:
    description: Permission of group create command.
    default: true
  undine.group.delete:
    description: Permission of group delete command.
    default: true
  undine.group.list:
    description: Permission of group list command.
    default: true
  undine.group.detail:
    description: Permission of group detail command.
    default: true
  undine.group.add:
    description: Permission of group add command.
    default: true
  undine.group.remove:
    description: Permission of group remove command.
    default: true
  undine.group.perm:
    description: Permission of group perm command.
    default: true
  undine.group.infinite-create:
    description: Permission of infinite create groups.
    default: op
  undine.group.infinite-add-member:
    description: Permission of infinite add members.
    default: op
  undine.group.modify-all:
    description: Permission of modification all groups.
    default: op
  undine.group.dissolution-all:
    description: Permission of break-up groups.
    default: op

  undine.group.*:
    description: All Permissions of Undine Group Management.
    children:
      undine.group.command: true
      undine.group.create: true
      undine.group.delete: true
      undine.group.list: true
      undine.group.detail: true
      undine.group.add: true
      undine.group.remove: true
      undine.group.perm: true
      undine.group.infinite-create: true
      undine.group.infinite-add-member: true
      undine.group.send-all: true
      undine.group.modify-all: true
      undine.group.dissolution-all: true

  undine.*:
    description: All Permissions of UndineMailer.
    children:
      undine.command: true
      undine.inbox: true
      undine.outbox: true
      undine.read: true
      undine.read-all: true
      undine.text: true
      undine.write: true
      undine.to: true
      undine.message: true
      undine.attach: true
      undine.attach-all: true
      undine.attach-infinity: true
      undine.costmoney: true
      undine.costitem: true
      undine.send: true
      undine.cancel: true
      undine.item: true
      undine.reload: true
      undine.list: true
      undine.group.*: true
